tasks:
  - gitRepositoryConfig:
      apiUrl: ${API_URL}
      apiToken: ${API_TOKEN}
    messageConfig:
      channels:
        - channelName: "any_ci_channel"
          webHookUrl: ${HOOK_FOR_CI_CHANNEL}
          notificationModifier: ""
          iconEmoji: ":smile:"
          username: "any bot name"
    taskConfig:
      periodAsHour: 2
      startingTimeAsHour: 10
      endingTimeAsHour: 18
startingTime: "08:40"