tasks:
  - gitRepositoryConfig:
      apiUrl: ${API_URL}
      apiToken: ${API_TOKEN}
    messageConfig:
      channelNameWebHookUrlMap:
        any_ci_channel: ${HOOK_FOR_CI_CHANNEL}
    taskConfig:
      periodAsHour: 2
      startingTimeAsHour: 10
      endingTimeAsHour: 18
startingTime: "08:40"